name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run flake8
      run: |
        flake8 src tests

    - name: Run black
      run: |
        black --check src tests

    - name: Run mypy
      run: |
        mypy src

    - name: Run isort
      run: |
        isort --check-only src tests

    - name: Run tests
      run: |
        pytest tests/test_main.py
